-- TB_POPUP_MST: 팝업(공지사항) 마스터 테이블 (PostgreSQL용)
-- 팝업 관리 및 사용자 표시를 위한 테이블

CREATE TABLE IF NOT EXISTS TB_POPUP_MST (
    POPUP_ID        SERIAL PRIMARY KEY,
    TITL            VARCHAR(200) NOT NULL,
    CONT            TEXT,
    IMG_PATH        VARCHAR(500),
    LNK_URL         VARCHAR(500),
    
    -- 기간 설정
    START_DT        TIMESTAMP NOT NULL,
    END_DT          TIMESTAMP NOT NULL,
    
    -- 표시 설정
    USE_YN          CHAR(1) DEFAULT 'Y',
    DISP_ORD        INTEGER DEFAULT 999,
    DISP_TYPE       VARCHAR(20) DEFAULT 'MODAL',
    
    -- 디자인 설정
    WIDTH           INTEGER DEFAULT 500,
    HEIGHT          INTEGER,
    BG_COLR         VARCHAR(7) DEFAULT '#FFFFFF',
    
    -- "보지 않기" 설정 (1~7일 중 선택)
    HIDE_OPT_YN     CHAR(1) DEFAULT 'Y',
    HIDE_DAYS_MAX   INTEGER DEFAULT 7 CHECK (HIDE_DAYS_MAX >= 1 AND HIDE_DAYS_MAX <= 7),
    
    -- 타겟 설정
    TARGET_ROLE     VARCHAR(50) DEFAULT 'ALL',
    TARGET_PAGES    VARCHAR(500) DEFAULT 'ALL',
    
    -- 메타데이터
    REG_DT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REG_USER_ID     VARCHAR(50),
    UPD_DT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_USER_ID     VARCHAR(50),
    DEL_YN          CHAR(1) DEFAULT 'N'
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_TB_POPUP_MST_USE_YN ON TB_POPUP_MST(USE_YN);
CREATE INDEX IF NOT EXISTS IDX_TB_POPUP_MST_DATE ON TB_POPUP_MST(START_DT, END_DT);
CREATE INDEX IF NOT EXISTS IDX_TB_POPUP_MST_ORD ON TB_POPUP_MST(DISP_ORD);

-- 테이블 및 컬럼 코멘트 (선택사항)
COMMENT ON TABLE TB_POPUP_MST IS '팝업 마스터 테이블';
COMMENT ON COLUMN TB_POPUP_MST.POPUP_ID IS '팝업 ID (PK)';
COMMENT ON COLUMN TB_POPUP_MST.TITL IS '팝업 제목';
COMMENT ON COLUMN TB_POPUP_MST.CONT IS '팝업 내용 (HTML 가능)';
COMMENT ON COLUMN TB_POPUP_MST.IMG_PATH IS '이미지 경로';
COMMENT ON COLUMN TB_POPUP_MST.LNK_URL IS '링크 URL (클릭 시 이동)';
COMMENT ON COLUMN TB_POPUP_MST.START_DT IS '팝업 시작일시';
COMMENT ON COLUMN TB_POPUP_MST.END_DT IS '팝업 종료일시';
COMMENT ON COLUMN TB_POPUP_MST.USE_YN IS '사용 여부 (Y/N)';
COMMENT ON COLUMN TB_POPUP_MST.DISP_ORD IS '표시 순서 (낮을수록 우선)';
COMMENT ON COLUMN TB_POPUP_MST.DISP_TYPE IS '표시 타입 (MODAL/SLIDE/BANNER)';
COMMENT ON COLUMN TB_POPUP_MST.WIDTH IS '팝업 너비 (px)';
COMMENT ON COLUMN TB_POPUP_MST.HEIGHT IS '팝업 높이 (px)';
COMMENT ON COLUMN TB_POPUP_MST.BG_COLR IS '배경색';
COMMENT ON COLUMN TB_POPUP_MST.HIDE_OPT_YN IS '숨김 옵션 표시 여부';
COMMENT ON COLUMN TB_POPUP_MST.HIDE_DAYS_MAX IS '최대 숨김 일수 (1-7일)';
COMMENT ON COLUMN TB_POPUP_MST.TARGET_ROLE IS '대상 역할 (ALL/ADMIN/USER)';
COMMENT ON COLUMN TB_POPUP_MST.TARGET_PAGES IS '표시 페이지 (쉼표구분, ALL=전체)';
COMMENT ON COLUMN TB_POPUP_MST.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_POPUP_MST.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN TB_POPUP_MST.UPD_DT IS '수정일시';
COMMENT ON COLUMN TB_POPUP_MST.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN TB_POPUP_MST.DEL_YN IS '삭제 여부 (Y/N)';
