-- TB_POPUP_MST 테이블 수정 스크립트
-- 타겟 페이지/역할 컬럼 제거 (모든 페이지에서 표시하도록 단순화)

-- 1. 먼저 기존 데이터 백업 (선택사항)
-- CREATE TABLE TB_POPUP_MST_BACKUP AS SELECT * FROM TB_POPUP_MST;

-- 2. 타겟 페이지 컬럼 제거
ALTER TABLE TB_POPUP_MST DROP COLUMN IF EXISTS TARGET_PAGES;

-- 3. 타겟 역할 컬럼 제거
ALTER TABLE TB_POPUP_MST DROP COLUMN IF EXISTS TARGET_ROLE;

-- 4. 팝업 위치 컬럼 추가 (9개 위치 지원)
-- TOP_LEFT, TOP_CENTER, TOP_RIGHT
-- CENTER_LEFT, CENTER, CENTER_RIGHT  
-- BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
ALTER TABLE TB_POPUP_MST ADD COLUMN IF NOT EXISTS LOC VARCHAR(20) DEFAULT 'CENTER';

-- 5. 위치 컬럼 코멘트
COMMENT ON COLUMN TB_POPUP_MST.LOC IS '팝업 위치 (TOP_LEFT, TOP_CENTER, TOP_RIGHT, CENTER_LEFT, CENTER, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT)';

-- 6. 수정된 테이블 구조 확인
-- \d TB_POPUP_MST;

-- 최종 테이블 구조:
-- POPUP_ID        SERIAL PRIMARY KEY
-- TITL            VARCHAR(200) NOT NULL
-- CONT            TEXT
-- IMG_PATH        VARCHAR(500)
-- LNK_URL         VARCHAR(500)
-- START_DT        TIMESTAMP NOT NULL
-- END_DT          TIMESTAMP NOT NULL
-- USE_YN          CHAR(1) DEFAULT 'Y'
-- DISP_ORD        INTEGER DEFAULT 999
-- DISP_TYPE       VARCHAR(20) DEFAULT 'MODAL'
-- WIDTH           INTEGER DEFAULT 500
-- HEIGHT          INTEGER
-- BG_COLR         VARCHAR(7) DEFAULT '#FFFFFF'
-- HIDE_OPT_YN     CHAR(1) DEFAULT 'Y'
-- HIDE_DAYS_MAX   INTEGER DEFAULT 7
-- REG_DT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- REG_USER_ID     VARCHAR(50)
-- UPD_DT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- UPD_USER_ID     VARCHAR(50)
-- DEL_YN          CHAR(1) DEFAULT 'N'
